### ISSUE TITLE
Entry for https://www.fliegwerk.com/projects

### ISSUE THREAD

**Issue by pklaschka** [fliegwerk/Schasch#1]
Just as a reminder: Even though the project isn't finished whatsoever, it would still be great to have an entry in https://www.fliegwerk.com/projects where we can also state the current stage of development etc.

Whoever would be up to that: Feel free to write it and either publish it yourself or send it to me for publication. This can, then, also serve as a project homepage :slightly_smiling_face:

**Comment by pklaschka** [comment]
@LordCMonkey Would you like to take this on?

**Comment by LordCMonkey** [comment]
Added Schasch as a project. Project is lacking a higher aspect ratio logo for the detail page.

**Comment by pklaschka** [comment]
@LordCMonkey Frankly, I find it good the way it is. As soon as the game is ready, we can add screenshots etc., but for now, that's great.

Could we maybe add some content below the inverted part? Currently, this looks kind of strange:

![image](https://user-images.githubusercontent.com/25147704/70815606-16ba5480-1dce-11ea-96b6-f055a878be98.png)

Thank you for your work so far and in advance for maybe some content below the inverted part :+1: :pray:

**Comment by pklaschka** [comment]
@Lordcmonkey Any update about this?

**Comment by LordCMonkey** [comment]
Delayed by only a month!
